export const authConstants = {
    USER_LOGIN: 'USER_LOGIN',

    USER_LOGOUT: "USERLOGOUT"
}

export const UserConstants ={
    GET_REAL_TIME_USERS: 'GET_REAL_TIME_USERS',
    GET_REALTIME_MESSAGES: ' GET_REALTIME_MESSAGES',
    GET_REALTIME_NEW_MESSAGES: 'GET_REALTIME_NEW_MESSAGES'
}